DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  hashedPassword VARCHAR(50) NOT NULL,
  bio TEXT,
  profilePic VARCHAR(255)
);

CREATE TABLE posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(50),
  caption TEXT NOT NULL,
  userId INTEGER NOT NULL,
  imageId INTEGER NOT NULL
);
