"""change image to image_url in posts

Revision ID: 601016eb8b0f
Revises: 58a1682633f5
Create Date: 2024-05-09 10:29:25.791212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601016eb8b0f'
down_revision = '58a1682633f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image_url', sa.String(length=1000), nullable=False))
        # batch_op.drop_column('image')
        batch_op.alter_column("image", new_column_name="image_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('image', sa.VARCHAR(length=1000), nullable=False))
        # batch_op.drop_column('image_url')
        batch_op.alter_column("image_url", new_column_name="image")

    # ### end Alembic commands ###
